Note
TarasProrok/notes-app pull request #4
Opened 2023-07-26 14:23 UTC by shr3000

Add files Note

2023-07-26 15:16 UTC, LionnoiL requested changes

2023-07-26 15:16 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/note/Note.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
як буде генеруватися в базі id? у нас він uuid.

2023-07-26 15:16 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/note/NoteService.java
> +        noteRepository.deleteById(id);
на вході String, значить може буде null. Потрібна перевірка. це у всіх методах потрібно зробити.

2023-07-26 15:16 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/note/NoteService.java
> +        if (note.getId() == null) {
сам note вже може бути null

2023-07-26 17:01 UTC, LionnoiL requested changes
каталог .idea запушився. потрібно його прибрати з гіта.

2023-07-26 17:22 UTC, bit-to-bit reviewed
А для чого в pull request додав каталог .idea?

2023-07-27 05:32 UTC, LionnoiL approved these changes

2023-07-27 06:24 UTC, TarasProrok approved these changes

2023-07-27 06:38 UTC, merged