db-migrations
TarasProrok/notes-app pull request #5
Opened 2023-07-26 16:49 UTC by bit-to-bit

2023-07-26 16:59 UTC, LionnoiL requested changes
Взагалі то питання чи ці sql файли пройдуть в H2?

2023-07-26 16:59 UTC, LionnoiL commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/notedb
потрібно щоб було для тестування база H2. postgres вже для продакшена.

2023-07-26 16:59 UTC, LionnoiL commented on src/main/resources/application.properties
> +spring.datasource.username=user
якщо є логін та пароль то потрібно ще докер прикладати та інструцію в рідмі файлі.

2023-07-26 16:59 UTC, LionnoiL commented on src/main/resources/db/migration/V2023.07.26.001__create-schema-access.sql
> +	updated_date date          not null,
created_date date та updated_date автоматично оновлюються в базі чи потрібно вручну ставити?

2023-07-26 16:59 UTC, LionnoiL commented on src/main/resources/db/migration/V2023.07.26.001__create-schema-access.sql
> +
а що потрібно робити окремий unique index для primary key?

2023-07-26 16:59 UTC, TarasProrok commented on src/main/resources/db/migration/V2023.07.26.001__create-schema-access.sql
найменування гендеру англ, укр, ... класифікація згідно ІСО... дата останнього редагування профілю. Це все треба? все так круто.

2023-07-26 17:02 UTC, TarasProrok commented on src/main/resources/db/migration/V2023.07.26.002__create-schema-notes.sql
найменування типу доступу двома мовами? А в нотатках немає поля Мітка чи Тег. Я бачу що є нижче окремо тег, дата свторення, дата коригування. А це все треба? Я думав все буде трохи простіше.

2023-07-26 18:55 UTC, LionnoiL approved these changes

2023-07-26 19:48 UTC, TarasProrok commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/notedb
порт не 9999?

2023-07-27 06:14 UTC, shr3000 approved these changes

2023-07-27 06:14 UTC, shr3000 commented on src/main/resources/db/migration/V2023.07.26.001__create-schema-access.sql
> +	updated_date date          not null,
gender_id    numeric(1)    not null default 0,
 Як що дефолт 0 то нот нуль зайве, та і взагалі може поки без гендеру?

2023-07-27 06:37 UTC, merged