created User Entity
TarasProrok/notes-app pull request #9
Opened 2023-07-28 14:02 UTC by TarasProrok

2023-07-28 16:58 UTC, bit-to-bit reviewed
Mapper не створював для User та UserDTO?

2023-07-28 16:58 UTC, bit-to-bit commented on src/main/java/com/ratatui/notes/user/User.java
> +        private UUID userId = UUID.randomUUID();
Потрібно замінити @private UUID userId = UUID.randomUUID()" на щось типу: 
@Id
@Column(name = "user_id")
@GeneratedValue(strategy = GenerationType.UUID)
private UUID private UUID userId;

2023-07-28 16:58 UTC, bit-to-bit commented on src/main/java/com/ratatui/notes/user/User.java
> +        private UUID genderId;
genderID має біти тип int

2023-07-28 16:58 UTC, bit-to-bit commented on src/main/java/com/ratatui/notes/user/User.java
> +        @OneToMany (mappedBy = "note_owner", cascade = CascadeType.REMOVE)
Чому CascadeType.REMOVE? Вважаєш, що якщо юзер видаляється, то треба всі його нотатки автоматично видалити? Я якщо він розшарив нотаток через груповий доступ, виходить що всі втратятять цінний рецепт і бабуся, і дідусь...

2023-07-28 16:58 UTC, bit-to-bit commented on src/main/java/com/ratatui/notes/user/UserService.java
> +        userRepository.save(user);
А як будемо апдейтити:
username (хоча може саме логін і не повинен змінюватись, це поле під питанням)
password
enabled
nickname
birthday
gender_id ???

2023-07-28 19:14 UTC, LionnoiL requested changes
Потрібно розібратися з цими коментарями. Можливе ще якісь будуть.

2023-07-28 19:14 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/user/UserService.java
> +        return userRepository.findAll();
Методи в сервісі повинні повертати вже dto об'єкти. А щоб це зробити потрібно мати мапер(конвертер).

2023-07-28 19:14 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/user/UserRepository.java
> +}
А тут не uuid замість String?

2023-07-28 19:14 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/user/User.java
> +        private String username;
пропоную поле переіменувати на email. в базі нехай лишається username. щоб у нас була реєстрація по пошті та паролю. або в же в html підписувати що це email.

2023-07-28 19:14 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/user/UserService.java
> +        user.setUserType(UserTypes.valueOf(userDTO.getUserType().name()));
не зрозумів. userDTO.getUserType().name() робим стрінг щоб по ньому зробити знову UserTypes? user.setUserType(userDTO.getUserType()); має працювати.

2023-07-28 19:14 UTC, LionnoiL commented on src/main/java/com/ratatui/notes/user/UserService.java
> +    public void updateUser(UserDTO userDTO) {
немає метода створення юзера.

2023-07-29 11:24 UTC, TarasProrok commented on src/main/java/com/ratatui/notes/user/User.java
> +        private UUID genderId;
виправив

2023-07-29 11:26 UTC, TarasProrok commented on src/main/java/com/ratatui/notes/user/User.java
> +        @OneToMany (mappedBy = "note_owner", cascade = CascadeType.REMOVE)
згоден. рецепти при видаленні юзера можна не видаляти. Що просто цей рядок видалити?

2023-07-29 11:27 UTC, TarasProrok commented on src/main/java/com/ratatui/notes/user/UserRepository.java
> +}
виправив

2023-07-29 11:28 UTC, TarasProrok commented on src/main/java/com/ratatui/notes/user/User.java
> +        private String username;
наче логічно. зробив поле email.

2023-07-29 11:30 UTC, TarasProrok commented on src/main/java/com/ratatui/notes/user/UserService.java
> +        user.setUserType(UserTypes.valueOf(userDTO.getUserType().name()));
виправив

2023-07-29 11:32 UTC, TarasProrok commented on src/main/java/com/ratatui/notes/user/User.java
> +        private UUID userId = UUID.randomUUID();
виправив

2023-07-29 12:50 UTC, shr3000 approved these changes
Я апрувлю, щоб не стопорити, бо нажаль зайти зміг тільки з мобільного.

2023-07-29 15:13 UTC, LionnoiL approved these changes

2023-07-29 16:12 UTC, merged